# Generated by Django 4.2.21 on 2025-06-08 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_module',
            name='module_video',
        ),
    ]
